# Generated by Django 5.1.4 on 2024-12-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SoilMoisture', models.FloatField(blank=True, null=True)),
                ('Temperature', models.FloatField(blank=True, null=True)),
                ('SoilHumidity', models.FloatField(blank=True, null=True)),
                ('Time', models.IntegerField(blank=True, null=True)),
                ('AirTemperature', models.FloatField(blank=True, null=True)),
                ('WindSpeed', models.FloatField(blank=True, null=True)),
                ('Airhumidity', models.FloatField(blank=True, null=True)),
                ('Windgust', models.FloatField(blank=True, null=True)),
                ('Pressure', models.FloatField(blank=True, null=True)),
                ('ph', models.FloatField(blank=True, null=True)),
                ('rainfall', models.FloatField(blank=True, null=True)),
                ('N', models.IntegerField(blank=True, null=True)),
                ('P', models.IntegerField(blank=True, null=True)),
                ('K', models.IntegerField(blank=True, null=True)),
                ('Status', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
