# Generated by Django 5.1.4 on 2024-12-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TreeCare', '0002_tree_cluster'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files')),
            ],
        ),
    ]
